### ISSUE TITLE
Game.java PR Todo

### ISSUE THREAD

**Issue by cwchou2016** [cwchou2016/PickRed#1]
- [x] 修改 playCard: [不要自動撿最高分的牌](https://github.com/MontyPan/PickRed/pull/1#discussion_r277581673)
- [x] 修改 FooPlayer 名稱
- [x] 移動 TestGame.java 位置
- [x] 修改 `public static boolean debug`：[為什麼更不能加 static？(QA)](https://github.com/MontyPan/PickRed/pull/1#discussion_r281895084)
- [x] TestGame.java 用 `exception` 來寫不通過的 test (https://github.com/MontyPan/PickRed/pull/1#discussion_r281900006)
- [x] `FooPlayer.playCard()` 一次撿兩張牌 (https://github.com/MontyPan/PickRed/pull/1#discussion_r281900676), (https://github.com/MontyPan/PickRed/pull/1#discussion_r281903828)
- [x] 移除 `roundLeft`
- [x] [為什麼這邊選擇用 is-a 而不是 has-a(QA)](https://github.com/MontyPan/PickRed/pull/1#discussion_r281900972)
- [x] [測試 `Game.pick()` (QA)](https://github.com/MontyPan/PickRed/pull/1#discussion_r281901530)

**Comment by cwchou2016** [comment]
- [x]  parameter 與 field 不同名字
- [x] 不需生成 instance 就可以測試 `pick()`
